

services:
  mysql-test:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
  postgresql-test:
    image: postgres:9.6
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgresql:/var/lib/postgresql
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
      POSTGRES_ROOT_PASSWORD: test
  redis:
    image: redis:latest
    command: redis-server
    volumes: 
      - redis:/data
    ports:
      - 6379:6379

volumes:
  mysql:
  postgresql:
  redis:
    driver: local